Productos\ManagerBundle\Entity\Configuracion:
    type: entity
    table: configuracion
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        configuracion:
            type: string
            nullable: false
            length: 80
            fixed: false
            comment: ''
        valor:
            type: string
            nullable: false
            length: 80
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
