Productos\ManagerBundle\Entity\ProductoComentarios:
    type: entity
    table: producto_comentarios
    indexes:
        producto_fk_idx:
            columns:
                - id_producto
        usuario_comentarios_fk_idx:
            columns:
                - id_usuario
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        comentario:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        fechaComentrio:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
            column: fecha_comentrio
    manyToOne:
        idProducto:
            targetEntity: Producto
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_producto:
                    referencedColumnName: id
            orphanRemoval: false
        idUsuario:
            targetEntity: Usuarios
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_usuario:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
