Productos\ManagerBundle\Entity\UsuariosBanco:
    type: entity
    table: usuarios_banco
    indexes:
        banco_usuario_idx:
            columns:
                - idusuario
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombreBanco:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: ''
            column: nombre_banco
        nombreTitular:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: ''
            column: nombre_titular
        tipoCuenta:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: ''
            column: tipo_cuenta
        numeroCuenta:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: ''
            column: numero_cuenta
        ciudadTitular:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
            column: ciudad_titular
        informacionExtra:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: informacion_extra
    manyToOne:
        idusuario:
            targetEntity: Usuarios
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idusuario:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
