Usuarios\ManagerBundle\Entity\EstadosProducto:
    type: entity
    table: estados_producto
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        estado:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        cierraVenta:
            type: boolean
            nullable: false
            comment: ''
            column: cierra_venta
    lifecycleCallbacks: {  }
