productos_negociacion_ofertar:
    path:     /ofertas/ofertar
    defaults: { _controller: ProductosNegociacionBundle:Ofertas:ofertar }
    methods:  [POST]
    
productos_negociacion_aceptar:
    path:     /ofertas/aceptar
    defaults: { _controller: ProductosNegociacionBundle:Ofertas:aceptarOferta }
    methods:  [POST]
    
productos_negociacion_rechazar:
    path:     /ofertas/rechazar
    defaults: { _controller: ProductosNegociacionBundle:Ofertas:rechazarOferta }
    methods:  [POST]
    
productos_negociacion_ver_ofertas_productos:
    path:     /ofertas/listar/{idproducto}
    defaults: { _controller: ProductosNegociacionBundle:Ofertas:listar, idproducto: null }
    methods:  [GET]
    
    
productos_negociacion_ver_ofertas_usuario:
    path:     /ofertas/listarusuario/{idusuario}
    defaults: { _controller: ProductosNegociacionBundle:Ofertas:listarUsuario, idusuario: null }
    methods:  [GET]