usuarios_historico:
    resource: "@UsuariosHistoricoBundle/Resources/config/routing.yml"
    prefix:   /

usuarios_metas:
    resource: "@UsuariosMetasBundle/Resources/config/routing.yml"
    prefix:   /

usuarios_localizacion:
    resource: "@UsuariosLocalizacionBundle/Resources/config/routing.yml"
    prefix:   /

productos_calificacion:
    resource: "@ProductosCalificacionBundle/Resources/config/routing.yml"
    prefix:   /

seguidores_manager:
    resource: "@SeguidoresManagerBundle/Resources/config/routing.yml"
    prefix:   /

usuarios_preferencias:
    resource: "@UsuariosPreferenciasBundle/Resources/config/routing.yml"
    prefix:   /

usuarios_consulta_preferencias:
    resource: "@UsuariosConsultaPreferenciasBundle/Resources/config/routing.yml"
    prefix:   /

productos_comentarios:
    resource: "@ProductosComentariosBundle/Resources/config/routing.yml"
    prefix:   /

productos_preguntas:
    resource: "@ProductosPreguntasBundle/Resources/config/routing.yml"
    prefix:   /

productos_negociacion:
    resource: "@ProductosNegociacionBundle/Resources/config/routing.yml"
    prefix:   /

productos_imagenes:
    resource: "@ProductosImagenesBundle/Resources/config/routing.yml"
    prefix:   /

productos_manager:
    resource: "@ProductosManagerBundle/Resources/config/routing.yml"
    prefix:   /

productos_creacion:
    resource: "@ProductosCreacionBundle/Resources/config/routing.yml"
    prefix:   /

usuarios_reputacion:
    resource: "@UsuariosReputacionBundle/Resources/config/routing.yml"
    prefix:   /

usuarios_manager:
    resource: "@UsuariosManagerBundle/Resources/config/routing.yml"
    prefix:   /

application_generico:
    resource: "@ApplicationGenericoBundle/Resources/config/routing.yml"
    prefix:   /

